# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Clone repo
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
    - name: Store required environment variables to .env
      run: echo ${{ secrets.ENV }} > .env
      
    - name: Store GCP service account key to key.json
      run: echo ${{ secrets.GCP_SVC_ACC_KEY }} > key.json

    - name: Authenticate with G Cloud CLI
      run: gcloud auth activate-service-account ${{ secrets.GCP_SVC_ACC }} --key-file=key.json

    - name: Deploy to Google App Engine
      run: gcloud app deploy app.yaml --project ${{ secrets.GCP_PROJ_NAME }}

    
