# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Clone repo
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Store required environment variables to .env
      run: echo ${{ secrets.ENV }} > .env

    - name: Publish app to Google App Engine
      uses: zxyle/publish-gae-action@v2.3
      with:
        # The service account email which will be used for authentication.
        service_account_email: ${{ secrets.GCP_SVC_ACC }}
        # The service account key which will be used for authentication.
        service_account_key: ${{ secrets.GCP_SVC_ACC_KEY }}
        # GAE project id
        project_id: ${{ secrets.GCP_PROJ_NAME }}

    
